const test=require("node:test"),assert=require("node:assert/strict"),vm=require("node:vm");
const mod=require("../lib/forms"),{buildFormsHandlers,decorateFormsBookPage,formsClaimGateFragment,BUILTIN_FORM}=mod;
const C="11111111-1111-4111-8111-111111111111",A="22222222-2222-4222-8222-222222222222",T="33333333-3333-4333-8333-333333333333";
function res(){return{statusCode:200,body:null,headers:{},contentType:null,status(n){this.statusCode=n;return this},json(x){this.body=x;return this},set(x){Object.assign(this.headers,x);return this},type(x){this.contentType=x;return this},send(x){this.body=x;return this}}}
function req(x={}){return{body:{},query:{},params:{},headers:{"content-type":"application/json"},...x}}
function coach(){return async()=>({user:{id:C,app_metadata:{role:"coach"},user_metadata:{role:"athlete"}}})}
function response(body,status=200){return{ok:status>=200&&status<300,status,text:async()=>typeof body==="string"?body:JSON.stringify(body)}}
class Element{constructor(tag){this.tagName=tag;this.children=[];this.listeners={};this.style={};this.value="";this.checked=false;this.textContent=""}append(...xs){this.children.push(...xs)}replaceChildren(...xs){this.children=[...xs]}addEventListener(type,fn){this.listeners[type]=fn}focus(){this.focused=true}}
function descendants(root){const out=[];for(const x of root.children){out.push(x,...descendants(x))}return out}
async function runSignShell(html,pending){const ids={status:new Element("p"),forms:new Element("div"),name:new Element("input"),role:new Element("select"),attest:new Element("input"),submit:new Element("button")},created=[],posts=[];ids.role.value="parent";const document={getElementById:id=>ids[id],createElement:tag=>{const x=new Element(tag);created.push(x);return x}},fetch=async(url,opt)=>{if(opt&&opt.method==="POST"){posts.push({url,opt});return{ok:true,json:async()=>({state:"signed"})}}return{ok:true,json:async()=>pending}};const script=html.match(/<script>([\s\S]*)<\/script>/)[1];vm.runInNewContext(script,{document,location:{pathname:`/sign/invite/${T}`},fetch,crypto:{randomUUID:()=>T},encodeURIComponent,Array,String,Number});await new Promise(setImmediate);return{ids,created,posts,click:()=>ids.submit.listeners.click.call(ids.submit)}}

test("exact exports, inert build, deeply immutable byte-exact built-in",()=>{assert.deepEqual(Object.keys(mod),["buildFormsHandlers","decorateFormsBookPage","formsClaimGateFragment","BUILTIN_FORM"]);let n=0;const h=buildFormsHandlers({requireSupabaseUser(){n++},notify(){n++},now(){n++},randomUUID(){n++}});assert.equal(n,0);assert.equal(Object.keys(h).length,16);assert.ok(Object.isFrozen(BUILTIN_FORM)&&Object.isFrozen(BUILTIN_FORM.questions));assert.equal(BUILTIN_FORM.form_key,"00000000-0000-4000-8000-000000000030");assert.match(BUILTIN_FORM.body,/electronically\.$/)});
test("protected validation beats auth",async()=>{let n=0;const h=buildFormsHandlers({requireSupabaseUser:async()=>{n++;return{error:"unauthorized",status:401}}});const cases=[[h.postCoachForm,req({body:{kind:"consent",title:"x",body:"x",questions:[],required:true,coach_id:C}})],[h.patchCoachForm,req({params:{id:"bad"},body:{version:1,title:"x"}})],[h.deleteCoachForm,req({params:{id:"bad"}})],[h.getFormResponses,req({params:{id:"bad"}})],[h.getAthleteForms,req({params:{id:"bad"}})]];for(const[x,r]of cases){const o=res();await x(r,o);assert.equal(o.statusCode,400)}assert.equal(n,0)});
test("public body rejects tenant and audit fields before capability",async()=>{let fetches=0;const old=global.fetch;global.fetch=async()=>{fetches++;throw 0};try{const h=buildFormsHandlers({});const o=res();await h.postInviteSign(req({params:{token:T},body:{submission_id:T,form_key:T,form_version:1,signer_name:"A B",signer_role:"athlete",guardian_attested:false,answers:{},coach_id:C,request_ip:"x"}}),o);assert.deepEqual([o.statusCode,o.body],[400,{error:"invalid_body"}]);assert.equal(fetches,0)}finally{global.fetch=old}});
test("role is app_metadata only",async()=>{const h=buildFormsHandlers({requireSupabaseUser:async()=>({user:{id:C,app_metadata:{},user_metadata:{role:"coach"}}})}),o=res();await h.getCoachForms(req(),o);assert.deepEqual([o.statusCode,o.body],[403,{error:"forbidden"}])});
test("malformed public capabilities normalize to indexed zero UUID lookup",async()=>{process.env.SUPABASE_URL="https://db.test";process.env.SUPABASE_SERVICE_KEY="k";const old=global.fetch,c=[];global.fetch=async u=>{c.push(String(u));return{ok:true,status:200,text:async()=>"[]"}};try{const h=buildFormsHandlers({});for(const fn of[h.getInviteForms,h.getClaimForms]){const o=res();await fn(req({params:{token:"bad"}}),o);assert.deepEqual([o.statusCode,o.body],[404,{error:"not_found"}])}assert.ok(c.every(x=>x.includes("token=eq.00000000-0000-0000-0000-000000000000")))}finally{global.fetch=old}});
test("HTML shells are invariant, no-store, safe-text and external-free",()=>{const h=buildFormsHandlers({});const a=res(),b=res();h.getInviteSignPage(req({params:{token:"one"}}),a);h.getInviteSignPage(req({params:{token:"two"}}),b);assert.equal(a.body,b.body);assert.equal(a.headers["Referrer-Policy"],"no-referrer");assert.match(a.body,/textContent/);assert.doesNotMatch(a.body,/innerHTML|https?:\/\//);assert.match(a.body,/width=device-width/)});
test("question-bearing shell safely renders and submits all seven answer types",async()=>{const q=(n,type,label,options=[])=>({id:`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`,type,label,required:true,options}),questions=[q(1,"short_text",'<img src=x onerror="alert(1)">'),q(2,"long_text","History & notes"),q(3,"single_choice","Pick one",["<script>bad()</script>","Blue"]),q(4,"multi_choice","Pick several",["A & B","C"]),q(5,"yes_no","Ready?"),q(6,"number","Score"),q(7,"date","Date")],h=buildFormsHandlers({}),page=res();h.getInviteSignPage(req({params:{token:T}}),page);const ui=await runSignShell(page.body,{state:"pending",forms:[{form_key:T,kind:"intake",title:"<svg onload=alert(1)>",body:"Body </section><script>bad()</script>",questions,required:true,version:1}]});assert.ok(ui.created.some(x=>x.tagName==="h2"&&x.textContent==="<svg onload=alert(1)>"));assert.ok(ui.created.some(x=>x.tagName==="legend"&&x.textContent.startsWith('<img src=x onerror="alert(1)">')));assert.ok(ui.created.some(x=>x.tagName==="option"&&x.textContent==="<script>bad()</script>"));assert.ok(!ui.created.some(x=>["img","svg","script"].includes(x.tagName)));await ui.click();assert.equal(ui.posts.length,0);assert.match(ui.ids.status.textContent,/required questions/);const nodes=descendants(ui.ids.forms),byName=new Map(nodes.filter(x=>x.name).map(x=>[x.name,x]));byName.get(questions[0].id).value=" Avery ";byName.get(questions[1].id).value="Long answer";byName.get(questions[2].id).value="Blue";byName.get(questions[4].id).value="false";byName.get(questions[5].id).value="12.5";byName.get(questions[6].id).value="2026-07-16";nodes.find(x=>x.tagName==="input"&&x.type==="checkbox"&&x.value==="A & B").checked=true;ui.ids.name.value="Avery Parent";ui.ids.attest.checked=true;await ui.click();assert.equal(ui.posts.length,1);const body=JSON.parse(ui.posts[0].opt.body);assert.deepEqual(body.answers,{[questions[0].id]:"Avery",[questions[1].id]:"Long answer",[questions[2].id]:"Blue",[questions[3].id]:["A & B"],[questions[4].id]:false,[questions[5].id]:12.5,[questions[6].id]:"2026-07-16"});assert.equal(ui.ids.status.textContent,"All forms are complete.")});
test("claim fragment uses encoded token and textContent",()=>{const x=formsClaimGateFragment();assert.match(x,/encodeURIComponent/);assert.match(x,/textContent/);assert.doesNotMatch(x,/innerHTML/)});
test("book decorator exact-anchor guards and safe DOM",()=>{const html='/* ---------- States: loading / error / empty ---------- */\n<p class="sub">Pick a time that works. No account, no forms.</p>\n<div id="timesArea" style="display:none">\nvar emptySlots = document.getElementById("emptySlots");\nshow(bookingEl);';const x=decorateFormsBookPage(html);assert.match(x,/Required forms come first/);assert.match(x,/encodeURIComponent/);assert.doesNotMatch(x,/innerHTML/);assert.throws(()=>decorateFormsBookPage(html+html))});
test("book gate offers optional forms without blocking and blocks required forms",async()=>{const html='/* ---------- States: loading / error / empty ---------- */\n<p class="sub">Pick a time that works. No account, no forms.</p>\n<div id="timesArea" style="display:none">\nvar emptySlots = document.getElementById("emptySlots");\nshow(bookingEl);',decorated=decorateFormsBookPage(html),source=decorated.match(/async function loadFormsGate\(\)[\s\S]*?\n\/\* COMPARE_GAP:FORMS:BOOK_LOGIC:END \*\//)[0].replace(/\n\/\*[\s\S]*$/,"");for(const [required,allowed] of [[false,true],[true,false]]){const fmLink=new Element("a"),fmGate=new Element("div"),fn=vm.runInNewContext(`(${source})`,{inviteToken:T,encodeURIComponent,fetch:async()=>({ok:true,json:async()=>({state:"pending",forms:[{required}]})}),document:{getElementById:id=>id==="fmLink"?fmLink:fmGate}});assert.equal(await fn(),allowed);assert.equal(fmGate.style.display,"block");assert.equal(fmLink.href,`/sign/invite/${T}`)}});

test("public pending DTO retains optional required=false while required forms may be clear",async()=>{process.env.SUPABASE_URL="https://db.test";process.env.SUPABASE_SERVICE_KEY="k";const old=global.fetch,optional={id:"44444444-4444-4444-8444-444444444444",coach_id:C,form_key:"55555555-5555-4555-8555-555555555555",kind:"intake",title:"Optional intake",body:null,questions:[],required:false,is_default:false,session_type_id:null,expires_days:null,active:true,version:1,created_at:"2026-07-01T00:00:00Z",updated_at:null};global.fetch=async url=>{url=String(url);if(url.includes("booking_invites?"))return response([{token:T,coach_id:C,athlete_id:A,status:"pending",expires_at:"2099-01-01T00:00:00Z"}]);if(url.includes("athletes?"))return response([{id:A,coach_id:C,name:"Avery"}]);if(url.includes("forms?"))return response([optional]);if(url.includes("form_signatures?"))return response([{form_key:BUILTIN_FORM.form_key,signed_at:"2026-07-15T00:00:00Z",expires_at:null}]);throw new Error(`unexpected ${url}`)};try{const h=buildFormsHandlers({now:()=>new Date("2026-07-16T12:00:00Z")}),o=res();await h.getInviteForms(req({params:{token:T}}),o);assert.equal(o.statusCode,200);assert.deepEqual(o.body,{state:"pending",forms:[{form_key:optional.form_key,kind:"intake",title:"Optional intake",body:null,questions:[],required:false,version:1}]})}finally{global.fetch=old}});
test("primitive argument validation is fail-closed before config",async()=>{const h=buildFormsHandlers({});await assert.rejects(()=>h.pendingFormsForAthlete({coachId:"bad",athleteId:A}),TypeError);await assert.rejects(()=>h.assertRequiredFormsSigned({coachId:C,athleteId:"bad",sessionTypeId:null}),TypeError);await assert.rejects(()=>h.notifyPendingWaiver({coachId:C,athleteId:A,slot:{id:"bad"}}),TypeError)});
test("2xx parse failure and transport rejection map to envelopes",async()=>{process.env.SUPABASE_URL="https://db.test";process.env.SUPABASE_SERVICE_KEY="k";const old=global.fetch,h=buildFormsHandlers({});try{global.fetch=async()=>({ok:true,status:200,text:async()=>"x"});let o=res();await h.getInviteForms(req({params:{token:T}}),o);assert.equal(o.statusCode,500);global.fetch=async()=>{throw new TypeError("secret")};o=res();await h.getInviteForms(req({params:{token:T}}),o);assert.deepEqual([o.statusCode,o.body],[502,{error:"upstream_unavailable"}])}finally{global.fetch=old}});

test("pending helper uses only the latest signature and does not revive an older one",async()=>{process.env.SUPABASE_URL="https://db.test";process.env.SUPABASE_SERVICE_KEY="k";const old=global.fetch,h=buildFormsHandlers({now:()=>new Date("2026-07-16T12:00:00Z")});global.fetch=async url=>{url=String(url);if(url.includes("athletes?"))return response([{id:A,coach_id:C,name:"Avery"}]);if(url.includes("forms?"))return response([]);if(url.includes("form_signatures?"))return response([{form_key:BUILTIN_FORM.form_key,signed_at:"2026-07-15T00:00:00Z",expires_at:"2026-07-16T11:59:59Z"},{form_key:BUILTIN_FORM.form_key,signed_at:"2026-07-14T00:00:00Z",expires_at:"2026-08-01T00:00:00Z"}]);throw new Error("unexpected fetch")};try{const pending=await h.pendingFormsForAthlete({coachId:C,athleteId:A,sessionTypeId:null,includeOptional:false});assert.deepEqual(pending.map(x=>x.form_key),[BUILTIN_FORM.form_key])}finally{global.fetch=old}});

test("equal signing retry returns 200 and re-emits the exact durable dedupe event",async()=>{process.env.SUPABASE_URL="https://db.test";process.env.SUPABASE_SERVICE_KEY="k";const old=global.fetch,events=[],sig="44444444-4444-4444-8444-444444444444";const h=buildFormsHandlers({notify:async x=>{events.push(x);throw new Error("down")}});global.fetch=async url=>{url=String(url);if(url.includes("booking_invites?"))return response([{token:T,coach_id:C,athlete_id:A,status:"pending",expires_at:"2099-01-01T00:00:00Z"}]);if(url.includes("form_signatures?"))return response([{id:sig,coach_id:C,athlete_id:A,form_key:BUILTIN_FORM.form_key,form_version:1,submission_id:T,signer_name:"Avery Parent",signer_role:"parent",guardian_attested:true,title_snapshot:BUILTIN_FORM.title,questions_snapshot:[],answers:{},signed_at:"2026-07-16T12:00:00Z",expires_at:null}]);if(url.includes("athletes?"))return response([{id:A,coach_id:C,name:"Avery"}]);throw new Error("unexpected fetch")};try{const o=res();await h.postInviteSign(req({params:{token:T},body:{submission_id:T,form_key:BUILTIN_FORM.form_key,form_version:1,signer_name:" Avery Parent ",signer_role:"parent",guardian_attested:true,answers:{}}}),o);assert.deepEqual([o.statusCode,o.body.state],[200,"signed"]);assert.equal(events.length,1);assert.equal(events[0].dedupeKey,`forms.signed:${sig}`);assert.deepEqual(Object.keys(events[0].data),["athleteId","formKey","href"])}finally{global.fetch=old}});

test("pending-waiver notification re-reads the owned slot and remains fail-soft",async()=>{process.env.SUPABASE_URL="https://db.test";process.env.SUPABASE_SERVICE_KEY="k";const old=global.fetch,events=[];const h=buildFormsHandlers({notify:async x=>{events.push(x);throw new Error("down")}});global.fetch=async url=>{url=String(url);if(url.includes("bookable_slots?"))return response([{id:T,coach_id:C,session_type_id:null}]);if(url.includes("athletes?"))return response([{id:A,coach_id:C,name:"Avery"}]);if(url.includes("forms?"))return response([]);if(url.includes("form_signatures?"))return response([]);throw new Error("unexpected fetch")};try{const x=await h.notifyPendingWaiver({coachId:C,athleteId:A,slot:{id:T,status:"booked"}});assert.deepEqual(x,{pending:1,notified:true});assert.equal(events[0].dedupeKey,`forms.pending:${A}:${T}`)}finally{global.fetch=old}});
